version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      REDIS_URI: redis://redis
    ports:
      - 8080:8080

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 3000:3000
